apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: kubedemofromjenkins
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: kubedemofromjenkins
  template:
    metadata: 
      labels:
        app: kubedemofromjenkins
    spec:
      containers:
      - name: kubedemofromjenkins
        image: kirandocker3887/mytomcatimage1:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: kubedemofromjenkins-svc 
  labels:
    app: kubedemofromjenkins 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 8009
    targetPort: 8080
  selector:
    app: kubedemofromjenkins
